//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Khachhang", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class Khachhang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int makhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ngaysinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenkhField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int makh {
            get {
                return this.makhField;
            }
            set {
                if ((this.makhField.Equals(value) != true)) {
                    this.makhField = value;
                    this.RaisePropertyChanged("makh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ngaysinh {
            get {
                return this.ngaysinhField;
            }
            set {
                if ((this.ngaysinhField.Equals(value) != true)) {
                    this.ngaysinhField = value;
                    this.RaisePropertyChanged("ngaysinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenkh {
            get {
                return this.tenkhField;
            }
            set {
                if ((object.ReferenceEquals(this.tenkhField, value) != true)) {
                    this.tenkhField = value;
                    this.RaisePropertyChanged("tenkh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hanghoa", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class Hanghoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string chungloaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float dongiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mahangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soluongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenhangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string chungloai {
            get {
                return this.chungloaiField;
            }
            set {
                if ((object.ReferenceEquals(this.chungloaiField, value) != true)) {
                    this.chungloaiField = value;
                    this.RaisePropertyChanged("chungloai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float dongia {
            get {
                return this.dongiaField;
            }
            set {
                if ((this.dongiaField.Equals(value) != true)) {
                    this.dongiaField = value;
                    this.RaisePropertyChanged("dongia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mahang {
            get {
                return this.mahangField;
            }
            set {
                if ((this.mahangField.Equals(value) != true)) {
                    this.mahangField = value;
                    this.RaisePropertyChanged("mahang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soluong {
            get {
                return this.soluongField;
            }
            set {
                if ((this.soluongField.Equals(value) != true)) {
                    this.soluongField = value;
                    this.RaisePropertyChanged("soluong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenhang {
            get {
                return this.tenhangField;
            }
            set {
                if ((object.ReferenceEquals(this.tenhangField, value) != true)) {
                    this.tenhangField = value;
                    this.RaisePropertyChanged("tenhang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hoadon", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class Hoadon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mahangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mahdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int makhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ngaymuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soluongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mahang {
            get {
                return this.mahangField;
            }
            set {
                if ((this.mahangField.Equals(value) != true)) {
                    this.mahangField = value;
                    this.RaisePropertyChanged("mahang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mahd {
            get {
                return this.mahdField;
            }
            set {
                if ((this.mahdField.Equals(value) != true)) {
                    this.mahdField = value;
                    this.RaisePropertyChanged("mahd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int makh {
            get {
                return this.makhField;
            }
            set {
                if ((this.makhField.Equals(value) != true)) {
                    this.makhField = value;
                    this.RaisePropertyChanged("makh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ngaymua {
            get {
                return this.ngaymuaField;
            }
            set {
                if ((this.ngaymuaField.Equals(value) != true)) {
                    this.ngaymuaField = value;
                    this.RaisePropertyChanged("ngaymua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soluong {
            get {
                return this.soluongField;
            }
            set {
                if ((this.soluongField.Equals(value) != true)) {
                    this.soluongField = value;
                    this.RaisePropertyChanged("soluong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Report", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class Report : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dongiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ngaymuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soluongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenhangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenkhField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dongia {
            get {
                return this.dongiaField;
            }
            set {
                if ((this.dongiaField.Equals(value) != true)) {
                    this.dongiaField = value;
                    this.RaisePropertyChanged("dongia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ngaymua {
            get {
                return this.ngaymuaField;
            }
            set {
                if ((this.ngaymuaField.Equals(value) != true)) {
                    this.ngaymuaField = value;
                    this.RaisePropertyChanged("ngaymua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soluong {
            get {
                return this.soluongField;
            }
            set {
                if ((this.soluongField.Equals(value) != true)) {
                    this.soluongField = value;
                    this.RaisePropertyChanged("soluong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenhang {
            get {
                return this.tenhangField;
            }
            set {
                if ((object.ReferenceEquals(this.tenhangField, value) != true)) {
                    this.tenhangField = value;
                    this.RaisePropertyChanged("tenhang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenkh {
            get {
                return this.tenkhField;
            }
            set {
                if ((object.ReferenceEquals(this.tenkhField, value) != true)) {
                    this.tenkhField = value;
                    this.RaisePropertyChanged("tenkh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loadkh", ReplyAction="http://tempuri.org/IService1/LoadkhResponse")]
        WindowsFormsApp1.ServiceReference1.Khachhang[] Loadkh();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loadkh", ReplyAction="http://tempuri.org/IService1/LoadkhResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Khachhang[]> LoadkhAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertkh", ReplyAction="http://tempuri.org/IService1/InsertkhResponse")]
        void Insertkh(WindowsFormsApp1.ServiceReference1.Khachhang hachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertkh", ReplyAction="http://tempuri.org/IService1/InsertkhResponse")]
        System.Threading.Tasks.Task InsertkhAsync(WindowsFormsApp1.ServiceReference1.Khachhang hachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatekh", ReplyAction="http://tempuri.org/IService1/UpdatekhResponse")]
        void Updatekh(WindowsFormsApp1.ServiceReference1.Khachhang hachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatekh", ReplyAction="http://tempuri.org/IService1/UpdatekhResponse")]
        System.Threading.Tasks.Task UpdatekhAsync(WindowsFormsApp1.ServiceReference1.Khachhang hachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletekh", ReplyAction="http://tempuri.org/IService1/DeletekhResponse")]
        void Deletekh(WindowsFormsApp1.ServiceReference1.Khachhang hachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletekh", ReplyAction="http://tempuri.org/IService1/DeletekhResponse")]
        System.Threading.Tasks.Task DeletekhAsync(WindowsFormsApp1.ServiceReference1.Khachhang hachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loadhh", ReplyAction="http://tempuri.org/IService1/LoadhhResponse")]
        WindowsFormsApp1.ServiceReference1.Hanghoa[] Loadhh();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loadhh", ReplyAction="http://tempuri.org/IService1/LoadhhResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Hanghoa[]> LoadhhAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserthh", ReplyAction="http://tempuri.org/IService1/InserthhResponse")]
        void Inserthh(WindowsFormsApp1.ServiceReference1.Hanghoa hanghoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserthh", ReplyAction="http://tempuri.org/IService1/InserthhResponse")]
        System.Threading.Tasks.Task InserthhAsync(WindowsFormsApp1.ServiceReference1.Hanghoa hanghoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatehh", ReplyAction="http://tempuri.org/IService1/UpdatehhResponse")]
        void Updatehh(WindowsFormsApp1.ServiceReference1.Hanghoa hanghoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatehh", ReplyAction="http://tempuri.org/IService1/UpdatehhResponse")]
        System.Threading.Tasks.Task UpdatehhAsync(WindowsFormsApp1.ServiceReference1.Hanghoa hanghoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletehh", ReplyAction="http://tempuri.org/IService1/DeletehhResponse")]
        void Deletehh(WindowsFormsApp1.ServiceReference1.Hanghoa hanghoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletehh", ReplyAction="http://tempuri.org/IService1/DeletehhResponse")]
        System.Threading.Tasks.Task DeletehhAsync(WindowsFormsApp1.ServiceReference1.Hanghoa hanghoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loadhd", ReplyAction="http://tempuri.org/IService1/LoadhdResponse")]
        WindowsFormsApp1.ServiceReference1.Hoadon[] Loadhd();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loadhd", ReplyAction="http://tempuri.org/IService1/LoadhdResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Hoadon[]> LoadhdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserthd", ReplyAction="http://tempuri.org/IService1/InserthdResponse")]
        void Inserthd(WindowsFormsApp1.ServiceReference1.Hoadon hadon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserthd", ReplyAction="http://tempuri.org/IService1/InserthdResponse")]
        System.Threading.Tasks.Task InserthdAsync(WindowsFormsApp1.ServiceReference1.Hoadon hadon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatehd", ReplyAction="http://tempuri.org/IService1/UpdatehdResponse")]
        void Updatehd(WindowsFormsApp1.ServiceReference1.Hoadon hadon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatehd", ReplyAction="http://tempuri.org/IService1/UpdatehdResponse")]
        System.Threading.Tasks.Task UpdatehdAsync(WindowsFormsApp1.ServiceReference1.Hoadon hadon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletehd", ReplyAction="http://tempuri.org/IService1/DeletehdResponse")]
        void Deletehd(WindowsFormsApp1.ServiceReference1.Hoadon hadon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletehd", ReplyAction="http://tempuri.org/IService1/DeletehdResponse")]
        System.Threading.Tasks.Task DeletehdAsync(WindowsFormsApp1.ServiceReference1.Hoadon hadon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSL", ReplyAction="http://tempuri.org/IService1/GetSLResponse")]
        int GetSL(string Mahang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSL", ReplyAction="http://tempuri.org/IService1/GetSLResponse")]
        System.Threading.Tasks.Task<int> GetSLAsync(string Mahang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSL_2", ReplyAction="http://tempuri.org/IService1/GetSL_2Response")]
        int GetSL_2(string Mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSL_2", ReplyAction="http://tempuri.org/IService1/GetSL_2Response")]
        System.Threading.Tasks.Task<int> GetSL_2Async(string Mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSL", ReplyAction="http://tempuri.org/IService1/UpdateSLResponse")]
        void UpdateSL(string Mahang, int SL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSL", ReplyAction="http://tempuri.org/IService1/UpdateSLResponse")]
        System.Threading.Tasks.Task UpdateSLAsync(string Mahang, int SL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/data", ReplyAction="http://tempuri.org/IService1/dataResponse")]
        WindowsFormsApp1.ServiceReference1.Report[] data(string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/data", ReplyAction="http://tempuri.org/IService1/dataResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Report[]> dataAsync(string month);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IService1>, WindowsFormsApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApp1.ServiceReference1.Khachhang[] Loadkh() {
            return base.Channel.Loadkh();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Khachhang[]> LoadkhAsync() {
            return base.Channel.LoadkhAsync();
        }
        
        public void Insertkh(WindowsFormsApp1.ServiceReference1.Khachhang hachhang) {
            base.Channel.Insertkh(hachhang);
        }
        
        public System.Threading.Tasks.Task InsertkhAsync(WindowsFormsApp1.ServiceReference1.Khachhang hachhang) {
            return base.Channel.InsertkhAsync(hachhang);
        }
        
        public void Updatekh(WindowsFormsApp1.ServiceReference1.Khachhang hachhang) {
            base.Channel.Updatekh(hachhang);
        }
        
        public System.Threading.Tasks.Task UpdatekhAsync(WindowsFormsApp1.ServiceReference1.Khachhang hachhang) {
            return base.Channel.UpdatekhAsync(hachhang);
        }
        
        public void Deletekh(WindowsFormsApp1.ServiceReference1.Khachhang hachhang) {
            base.Channel.Deletekh(hachhang);
        }
        
        public System.Threading.Tasks.Task DeletekhAsync(WindowsFormsApp1.ServiceReference1.Khachhang hachhang) {
            return base.Channel.DeletekhAsync(hachhang);
        }
        
        public WindowsFormsApp1.ServiceReference1.Hanghoa[] Loadhh() {
            return base.Channel.Loadhh();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Hanghoa[]> LoadhhAsync() {
            return base.Channel.LoadhhAsync();
        }
        
        public void Inserthh(WindowsFormsApp1.ServiceReference1.Hanghoa hanghoa) {
            base.Channel.Inserthh(hanghoa);
        }
        
        public System.Threading.Tasks.Task InserthhAsync(WindowsFormsApp1.ServiceReference1.Hanghoa hanghoa) {
            return base.Channel.InserthhAsync(hanghoa);
        }
        
        public void Updatehh(WindowsFormsApp1.ServiceReference1.Hanghoa hanghoa) {
            base.Channel.Updatehh(hanghoa);
        }
        
        public System.Threading.Tasks.Task UpdatehhAsync(WindowsFormsApp1.ServiceReference1.Hanghoa hanghoa) {
            return base.Channel.UpdatehhAsync(hanghoa);
        }
        
        public void Deletehh(WindowsFormsApp1.ServiceReference1.Hanghoa hanghoa) {
            base.Channel.Deletehh(hanghoa);
        }
        
        public System.Threading.Tasks.Task DeletehhAsync(WindowsFormsApp1.ServiceReference1.Hanghoa hanghoa) {
            return base.Channel.DeletehhAsync(hanghoa);
        }
        
        public WindowsFormsApp1.ServiceReference1.Hoadon[] Loadhd() {
            return base.Channel.Loadhd();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Hoadon[]> LoadhdAsync() {
            return base.Channel.LoadhdAsync();
        }
        
        public void Inserthd(WindowsFormsApp1.ServiceReference1.Hoadon hadon) {
            base.Channel.Inserthd(hadon);
        }
        
        public System.Threading.Tasks.Task InserthdAsync(WindowsFormsApp1.ServiceReference1.Hoadon hadon) {
            return base.Channel.InserthdAsync(hadon);
        }
        
        public void Updatehd(WindowsFormsApp1.ServiceReference1.Hoadon hadon) {
            base.Channel.Updatehd(hadon);
        }
        
        public System.Threading.Tasks.Task UpdatehdAsync(WindowsFormsApp1.ServiceReference1.Hoadon hadon) {
            return base.Channel.UpdatehdAsync(hadon);
        }
        
        public void Deletehd(WindowsFormsApp1.ServiceReference1.Hoadon hadon) {
            base.Channel.Deletehd(hadon);
        }
        
        public System.Threading.Tasks.Task DeletehdAsync(WindowsFormsApp1.ServiceReference1.Hoadon hadon) {
            return base.Channel.DeletehdAsync(hadon);
        }
        
        public int GetSL(string Mahang) {
            return base.Channel.GetSL(Mahang);
        }
        
        public System.Threading.Tasks.Task<int> GetSLAsync(string Mahang) {
            return base.Channel.GetSLAsync(Mahang);
        }
        
        public int GetSL_2(string Mahd) {
            return base.Channel.GetSL_2(Mahd);
        }
        
        public System.Threading.Tasks.Task<int> GetSL_2Async(string Mahd) {
            return base.Channel.GetSL_2Async(Mahd);
        }
        
        public void UpdateSL(string Mahang, int SL) {
            base.Channel.UpdateSL(Mahang, SL);
        }
        
        public System.Threading.Tasks.Task UpdateSLAsync(string Mahang, int SL) {
            return base.Channel.UpdateSLAsync(Mahang, SL);
        }
        
        public WindowsFormsApp1.ServiceReference1.Report[] data(string month) {
            return base.Channel.data(month);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Report[]> dataAsync(string month) {
            return base.Channel.dataAsync(month);
        }
    }
}
